### ISSUE TITLE
Compiler error using latest ImGui due to api breaks.

### ISSUE THREAD

**Issue by leonsal** [epezent/implot#124]
Hi,

Latest ImGui has some api breaking changes which causes compilation errors for ImPlot: 

```
implot.cpp: In function ‘void ImPlot::AddTextVertical(ImDrawList*, ImVec2, ImU32, const char*, const char*)’:
implot.cpp:260:36: error: ‘struct ImFont’ has no member named ‘DisplayOffset’
  260 |     pos.x = IM_FLOOR(pos.x + font->DisplayOffset.y);
      |                                    ^~~~~~~~~~~~~
imgui/imgui_internal.h:202:55: note: in definition of macro ‘IM_FLOOR’
  202 | #define IM_FLOOR(_VAL)                  ((float)(int)(_VAL))                                    // ImFloor() is not inlined in MSVC debug builds
      |                                                       ^~~~
implot/implot.cpp:261:36: error: ‘struct ImFont’ has no member named ‘DisplayOffset’
  261 |     pos.y = IM_FLOOR(pos.y + font->DisplayOffset.x);
      |                                    ^~~~~~~~~~~~~
```

Regards.

**Comment by epezent** [comment]
Thanks. I've temporarily removed the `DisplayOffset`. Seems we could use `ImFontConfig::GlyphOffset` instead, but I don't think either are really necessary here. 

https://github.com/ocornut/imgui/commit/c206a193737811193a0b48ef2d35fe028fa0996e

**Comment by sonoro1234** [comment]
Yes but v0.7 (last tagged version) still has that making a problem for cimplot with last 1.79 cimgui

**Comment by andrewmcdonald-oxb** [comment]
Hello, do you think you'll be cutting an official 0.8 release to include this?

**Comment by epezent** [comment]
I was trying to squeeze a new feature I'm working on into 0.8, but since I'm being slow about it, I'll go ahead and push 0.8.

**Comment by andrewmcdonald-oxb** [comment]
That's great, thanks! It helps us audit our external library dependencies.
