### ISSUE TITLE
Compilation error after refactor

### ISSUE THREAD

**Issue by leonsal** [epezent/implot#93]
Hi,

After last refactor, I got the following compilation errors with gcc 9.3.0:
```
implot_items.cpp:247:20: error: specializing member ‘ImPlot::MaxIdx<short unsigned int>::Value’ requires ‘template<>’ syntax
  247 | const unsigned int MaxIdx<unsigned short>::Value = 65535;
      |                    ^~~~~~~~~~~~~~~~~~~~~~
implot_items.cpp:248:20: error: specializing member ‘ImPlot::MaxIdx<unsigned int>::Value’ requires ‘template<>’ syntax
  248 | const unsigned int MaxIdx<unsigned int>::Value   = 4294967295;
      |                    ^~~~~~~~~~~~~~~~~~~~
```
Regards,

**Comment by epezent** [comment]
Thanks for the heads up. I forgot to test GCC. Go figure. Can you see if the latest commit fixes the issue for you? Worked on GCC 8.3 for me.

**Comment by leonsal** [comment]
Demo compiled and executed OK with gcc 9.3.0 and clang 10.0.0 in Ubuntu Linux 20.04.1 LTS.
Thanks and congratulations for your amazing library.
